# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause or Apache-2.0

# usage: VERSION=... conda build conda/ --output-folder conda/out/
# use `craft_packages.py --conda` to build for all platforms

{% set pyproject = load_file_data("pyproject.toml") %}

package:
  name: pypdfium2
  version: {{ environ["VERSION"] }}

source:
  # using a local `git_url` instead of `path` so conda excludes generated directories from copying,
  # else it would take eternally if a sourcebuild was made previously
  git_url: ../..

build:
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script_env:
    - PDFIUM_BINARY
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  number: 0
  # FIXME pypdfium2 is arch specific but python independent
  # If we have `noarch: python` we will be python independent but incorrect, if we don't have it we will be correct but tied to a specific python version
  # So we see the following options, each with their own complications:
  # - Build python specific packages (inelegant, but the only choice supported by conda)
  # - Get conda changed (would be clean, but out of our hands)
  # - Edit the generated archives (risky, but might achieve what we want)
  # For now, we decided to build python specific packages, though it will consume a lot more CI runtime than PyPI packages.

requirements:
  build:
    - python
    - setuptools
    - build
    - wheel !=0.38.0,!=0.38.1
    # TODO consider using the pre-generated bindings file so we don't have to rely on a package of our ctypesgen fork (which is currently supplied by a third party)
    - ctypesgen-pypdfium2-team
    - pip
  run:
    - python

about:
  summary: {{ pyproject["project"]["description"] }}
  license: {{ pyproject["project"]["license"]["text"] }}
  license-files: {{ pyproject["tool"]["setuptools"]["license-files"] }}
  dev_url: {{ pyproject["project"]["urls"]["homepage"] }}
  doc_url: {{ pyproject["project"]["urls"]["documentation"] }}

extra:
  recipe-maintainers:
    - mara004
