# SPDX-FileCopyrightText: 2023 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

# NOTE
# 
# This branch attempted to bundle the pdfium binaries with conda packages, like we do for pypi wheels.
# However, conda does not support arch specific but python version independent packages, so we'd have to build for each version separately, which is not elegant.
# Also, bundling dynamic libraries is against the spirit of conda (as a system package manager), contrary to PyPI (as python only).
# 
# Therefore, the clean solution would be to package pdfium-binaries separately on conda, so pypdfium2 can just depend on pdfium and be noarch.
# This will require a new setup mode to bundle bindings only, and a way to pass additional runtime libdirs to ctypesgen.
# Also we may need to pin the pdfium requirement to the exact version the bindings were built for. (Strictly speaking, binaries and bindings belong together. This may not seem overly relevant since ctypesgen makes if guards for symbols and pdfium's public API is very stable, but in principle mismatched bindings can cause undefined behavior if parameters changed.)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# FIXME since conda isolates each build, our data/ cache is no use...

# usage: VERSION=... conda build conda/ --output-folder conda/out/
# use `craft_packages.py --conda` to build for all platforms

{% set pyproject = load_file_data("pyproject.toml") %}

package:
  name: pypdfium2
  version: {{ environ["VERSION"] }}

source:
  # using a local `git_url` instead of `path` so conda excludes generated directories from copying,
  # else it would take eternally if a sourcebuild was made previously
  git_url: ../..

build:
  entry_points:
    - pypdfium2 = pypdfium2.__main__:cli_main
  script_env:
    - PDFIUM_BINARY
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  number: 0

requirements:
  # FIXME not sure about conda's build/host distinction
  # FIXME adds awkward hashes to filename
  build:
    - {{ compiler('c') }}
    - git
  host:
    - python
    - pip
    - setuptools
    - python-build
    - wheel !=0.38.0,!=0.38.1
    # TODO consider using the pre-generated bindings file so we don't have to rely on a package of our ctypesgen fork (which is currently supplied by a third party)
    - ctypesgen-pypdfium2-team
  run:
    - python

about:
  summary: {{ pyproject["project"]["description"] }}
  license: {{ pyproject["project"]["license"]["text"] }}
  license-files: {{ pyproject["tool"]["setuptools"]["license-files"] }}
  dev_url: {{ pyproject["project"]["urls"]["homepage"] }}
  doc_url: {{ pyproject["project"]["urls"]["documentation"] }}

extra:
  recipe-maintainers:
    - mara004
